### ISSUE TITLE
rollover behavior with arguments for 'right side' increments

### ISSUE THREAD

**Issue by dwapstra** [mbarkhau/bumpver#154]
Should an update to a 'left side' field allow 'right side' fields to be updated if an argument is specified to do so?

Example use case: the minor version should start at '1' instead of '0'.

```toml
[bumpver]
current_version = "26.1"
version_pattern = "MAJOR.MINOR[.PATCH][PYTAGNUM]"
```

Major version update does a rollover and resets minor field to 0:

```
$ bumpver update --major
INFO    - Old Version: 26.1
INFO    - New Version: 27.0
```

Adding a 'minor' version update to the same command does not affect the minor version field.

```
$ bumpver update --major --minor
INFO    - Old Version: 26.1
INFO    - New Version: 27.0
```

Should the minor argument increment the minor version in this case or is the default rollover behavior preferred?
