### ISSUE TITLE
[feature request] allow --no-fetch to be configured from config file

### ISSUE THREAD

**Issue by tandav** [mbarkhau/bumpver#231]
It would be handy to configure `--no-fetch` from `pyproject.toml` or `setup.cfg`
for example:

```toml
[tool.bumpver]
fetch = false
```
