### ISSUE TITLE
Allow customizing tag NAME like `tag_message`

### ISSUE THREAD

**Issue by pirate** [mbarkhau/bumpver#240]
We prefix all our git tags that are for versions with `v`, so a tag for `0.8.5rc51` would be `v0.8.5rc51`.

Currently it's possible to customize the `tag_message` but it doesn't seem to affect the tag *name*.

```bash
$ bumpver update --tag-num
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Old Version: 0.8.5rc51
INFO    - New Version: 0.8.5rc52
INFO    - git commit --message 'bump version 0.8.5rc51 -> 0.8.5rc52'
INFO    - git tag --annotate 0.8.5rc52 --message 'v0.8.5rc52'  # both should be v0.8.5...
INFO    - git push origin --follow-tags 0.8.5rc52 HEAD         # should be v0.8.5...
```

**Comment by mbarkhau** [comment]
Hi @pirate

I'm not sure I follow. If you simply prefix your `version_pattern` with a `v`, does that not work?

```
$ bumpver test 'v0.8.5rc51' 'vMAJOR.MINOR.PATCH[TAGNUM]' --tag-num
New Version: v0.8.5rc52
PEP440     : 0.8.5rc52
```


Does your configuration look something like this?

```toml
[bumpver]
current_version = "v0.8.5rc51"
version_pattern = "vMAJOR.MINOR.PATCH[TAGNUM]"
```

**Comment by effigies** [comment]
I have a use case for this. I have a repository that is primarily versioning a document, but contains a Python package that is used to assist in rendering and provide programmatic access to the schema that's used for rendering. We typically have a series of git tags like:

* 1.9.0 - document
* schema-0.5.0 - package
* schema-0.5.1 - package
* 1.9.1 - document
* schema-0.6.0 - package
* ...

I would only be using `bumpver` to perform the `schema-*` tags, so I would like to be able to use:

```toml
[tool.bumpver]
current_version = "1.0.2-dev"
version_pattern = "MAJOR.MINOR.PATCH[-TAG]"
commit_message = "chore: Bump schema package to {version}"
tag = "schema-{version}"
tag_message = "schema-{version}"
push = false

[tool.bumpver.file_patterns]
"src/package/data/schema/SCHEMA_VERSION" = ['{version}']
```

**Comment by mbarkhau** [comment]
Yes that's correct, but I should note that `{version}` is just a shorthand and you can use the same syntax as with `version_pattern`.

In other words, this should also work:

```toml
[bumpver.file_patterns]
"VERSION" = ['MAJOR.MINOR.PATCH[-TAG]']
```

```bash
mbarkhau@devbox:~/bumpver-scratch$ cat bumpver.toml
[bumpver]
current_version = "schema-1.2.9-dev"
version_pattern = "schema-MAJOR.MINOR.PATCH[-TAG]"
commit_message = "chore: Bump schema package to {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"VERSION" = ['MAJOR.MINOR.PATCH[-TAG]']

mbarkhau@devbox:~/bumpver-scratch$ uvx bumpver update -n -p
INFO    - Old Version: schema-1.2.9-dev
INFO    - New Version: schema-1.2.10-dev
mbarkhau@devbox:~/bumpver-scratch$ cat VERSION
1.2.10-dev
mbarkhau@devbox:~/bumpver-scratch$ cat bumpver.toml
[bumpver]
current_version = "schema-1.2.10-dev"
version_pattern = "schema-MAJOR.MINOR.PATCH[-TAG]"
commit_message = "chore: Bump schema package to {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
commit = false
tag = false
push = false

[bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"VERSION" = ['MAJOR.MINOR.PATCH[-TAG]']
```
