### ISSUE TITLE
Bumpver update --commit cannot be invoked unless in the root of the project

### ISSUE THREAD

**Issue by yannsartori** [mbarkhau/bumpver#245]
Hello,

I noticed that `bumpver update --commit` cannot be invoked unless in the root of the project (at least for git). 

## Minimal reproduction:

1. `mkdir project`
2. `cd project`
3. `git init`
4. `mkdir a`
5. Create `a/pyproject.toml` with the following contents:

    ```toml
    [project]
    name = "a"
    version = "0.1.0"
    requires-python = ">=3"
    dependencies = ["bumpver"]


    [tool.bumpver]
    current_version = "0.1.0"
    version_pattern = "MAJOR.MINOR.PATCH"

    [tool.bumpver.file_patterns]
    "pyproject.toml" = ['^version = "{version}"', '^current_version = "{version}"']
    ```

6. `pip install -e .`
7. `git add pyproject.toml`
8. `git commit -m "commit"`
9. Run `bumpver update --patch --commit`, observe output

    ```text
    INFO    - Old Version: 0.1.0
    INFO    - New Version: 0.1.1
    WARNING - Version Control System not found, skipping commit.
    ```

## Potential Fix

In `vcs.py`, `VCSAPI::is_usable`, there is a check

```python
if not os.path.exists(f".{self.name}"):
    return False
```

which will obviously fail if not in the root. I don't think this check is necessary (at least for `git`), because you then invoke `self.subcommands['is_usable']`, which for `git` is `git rev-parse --git-dir` and works anywhere in the `git` project. I'm not sure if this is true for mercurial though.

I can open a PR to remove that check, but I just wanted to verify that it is indeed unnecessary before removing.
